package cn.lwq.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_age
     *
     * @mbggenerated
     */
    private Integer uAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_pwd
     *
     * @mbggenerated
     */
    private String uPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_phone
     *
     * @mbggenerated
     */
    private String uPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_time
     *
     * @mbggenerated
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_ftime
     *
     * @mbggenerated
     */
    private Date uFtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_ltime
     *
     * @mbggenerated
     */
    private Date uLtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_age
     *
     * @return the value of user.u_age
     *
     * @mbggenerated
     */
    public Integer getuAge() {
        return uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_age
     *
     * @param uAge the value for user.u_age
     *
     * @mbggenerated
     */
    public void setuAge(Integer uAge) {
        this.uAge = uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_pwd
     *
     * @return the value of user.u_pwd
     *
     * @mbggenerated
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_pwd
     *
     * @param uPwd the value for user.u_pwd
     *
     * @mbggenerated
     */
    public void setuPwd(String uPwd) {
        this.uPwd = uPwd == null ? null : uPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_email
     *
     * @return the value of user.u_email
     *
     * @mbggenerated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_email
     *
     * @param uEmail the value for user.u_email
     *
     * @mbggenerated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_phone
     *
     * @return the value of user.u_phone
     *
     * @mbggenerated
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_phone
     *
     * @param uPhone the value for user.u_phone
     *
     * @mbggenerated
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone == null ? null : uPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_time
     *
     * @return the value of user.u_time
     *
     * @mbggenerated
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_time
     *
     * @param uTime the value for user.u_time
     *
     * @mbggenerated
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_ftime
     *
     * @return the value of user.u_ftime
     *
     * @mbggenerated
     */
    public Date getuFtime() {
        return uFtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_ftime
     *
     * @param uFtime the value for user.u_ftime
     *
     * @mbggenerated
     */
    public void setuFtime(Date uFtime) {
        this.uFtime = uFtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_ltime
     *
     * @return the value of user.u_ltime
     *
     * @mbggenerated
     */
    public Date getuLtime() {
        return uLtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_ltime
     *
     * @param uLtime the value for user.u_ltime
     *
     * @mbggenerated
     */
    public void setuLtime(Date uLtime) {
        this.uLtime = uLtime;
    }
}